version: '3.6'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - '8081:8080'
    restart: always
    command:
      - '-Dkeycloak.profile.feature.upload_scripts=enabled'
    environment:
      PROXY_ADDRESS_FORWARDING: ${PROXY_ADDRESS_FORWARDING}
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_DATABASE}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
  api:
    image: 'vertexstudio.azurecr.io/medixlab-api:latest'
    ports:
      - '8000:8000'
    restart: always
    environment:
      LISTEN_URL: ${LISTEN_URL}
      DATABASE_URL: ${DATABASE_URL}
      RUST_LOG: ${RUST_LOG}
