version: '3.6'
services:
  postgres:
    image: postgres:13
    restart: always
    environment: 
      DATABASE_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    ports: 
        - "5432:5432"
    volumes: 
        - postgres_data:/var/lib/postgresql/data 
        - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - 8081:8080
    depends_on:
      - postgres
    restart: always
    command:
      - '-Dkeycloak.profile.feature.upload_scripts=enabled'
      - '-Dkeycloak.migration.action=import'
      - '-Dkeycloak.migration.provider=singleFile'
      - '-Dkeycloak.migration.file=/tmp/master-realm.json'
      - '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING'
    volumes:
      - type: bind
        source: './keycloak/master-realm.json'
        target: '/tmp/master-realm.json'
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_DATABASE}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
  api:
    image: 'vertexstudio.azurecr.io/medixlab-api:latest'
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    restart: always
    environment:
      LISTEN_URL: ${LISTEN_URL}
      DATABASE_URL: ${DATABASE_URL}
      RUST_LOG: ${RUST_LOG}
volumes:
  postgres_data:
